/* eslint-disable import/prefer-default-export */
export const FETCH_ALL_QUESTIONS_REQUEST = 'FETCH_ALL_QUESTIONS_REQUEST ';
export const FETCH_ALL_QUESTIONS_SUCCESS = 'FETCH_ALL_QUESTIONS_SUCCESS';
export const FETCH_ALL_QUESTIONS_FAILURE = 'FETCH_ALL_QUESTIONS_FAILURE';
