/* eslint-disable import/prefer-default-export */
export const FETCH_ALL_QUESTIONS_REQUEST = 'FETCH_ALL_QUESTIONS_REQUEST ';
export const FETCH_ALL_QUESTIONS_SUCCESS = 'FETCH_ALL_QUESTIONS_SUCCESS';
export const FETCH_ALL_QUESTIONS_FAILURE = 'FETCH_ALL_QUESTIONS_FAILURE';

// FILTERS REDUCERS
export const SET_FILTERS = 'SET_FILTERS';
export const CLEAR_FILTERS = 'CLEAR_FILTERS';

// UI REDUCER
export const TOGGLE_CHAPTERS_VISIBLE = 'TOGGLE_CHAPTERS_VISIBLE';
export const TOGGLE_ANSWERS_VISIBLE = 'TOGGLE_ANSWERS_VISIBLE';

// VISIBLE QUESTIONS REDUCER
export const SET_VISIBLE_QUESTIONS = 'SET_VISIBLE_QUESTIONS';
export const CLEAR_VISIBLE_QUESTIONS = 'CLEAR_VISIBLE_QUESTIONS';
